### ISSUE TITLE
Error in Highlight Mode

### ISSUE THREAD

**Issue by stevencox** [frostyfan109/tranql#106]
I opened the app, loaded one of the simple RTX graphs in 2D mode.

Selected the highlight tool and selected a node in the graph.

That produced this error:

![image](https://user-images.githubusercontent.com/306971/62585102-273d4a00-b885-11e9-81e3-64bac1682878.png)

**Comment by frostyfan109** [comment]
That is really peculiar, and I can't recreate it.

It shouldn't be possible because it requires an element to be getting unhighlighted when it was never highlighted in the first place.

**Comment by frostyfan109** [comment]
I got it to happen, but the way you get in the situation where the bug occurs remains a mystery. Somehow App::state::vMode can become undefined, which results in this error.

Edit: It's because the state variable is visMode, not vMode...

**Comment by frostyfan109** [comment]
Nevermind, this just happens when you clear the cache and never set vMode I guess. Did the default vMode somehow get deleted from the state?
