### ISSUE TITLE
Browse + Answer Viewer

### ISSUE THREAD

**Issue by stevencox** [frostyfan109/tranql#108]
Perhaps we should disable the answer viewer when browsing is happening.

![image](https://user-images.githubusercontent.com/306971/62585444-cf9fde00-b886-11e9-8313-711d33edfd78.png)
![image](https://user-images.githubusercontent.com/306971/62585453-daf30980-b886-11e9-83fb-f34f491049da.png)

**Comment by frostyfan109** [comment]
~I keep forgetting to check, but I think the answer viewer may have been broken again sadly, which would mean this isn't browse node-specific.~ Nevermind, it seems to be working properly without browsing.

**Comment by frostyfan109** [comment]
The original error has been fixed. Now the interface just looks like this:
![image](https://user-images.githubusercontent.com/31631417/62648730-65884700-b921-11e9-9ac6-a808a65e982a.png)

However, I think I found the culprit of what causes the blank interface:
```
{
  "nodes": [
    {
      "id": "n0",
      "curie": "DOID:12918",
      "type": "disease"
    },
    {
      "id": "n1",
      "type": "gene"
    },
    {
      "id": "n0",
      "curie": "DOID:1588",
      "type": "disease"
    },
    {
      "id": "n1",
      "type": "gene"
    }
  ],
  "edges": [
    {
      "id": "e0",
      "source_id": "n0",
      "target_id": "n1",
      "directed": true
    },
    {
      "id": "e0",
      "source_id": "n0",
      "target_id": "n1",
      "directed": true
    }
  ]
}
```
If ids matter to Robokop, then this is a really problem.

**Comment by stevencox** [comment]
Something must have changed in generate question. We should create one node with multiple identifiers.

**Comment by frostyfan109** [comment]
The nodes with curies are being generated by the Robokop API when browse nodes is used. Robokop then returns the results along with this question_graph which we merge into the current question_graph.

**Comment by frostyfan109** [comment]
This is the question_graph from the same query without browsing nodes, so maybe I was wrong and `generate_questions` is messed up.

```
{
  "nodes": [
    {
      "id": "n0",
      "curie": "DOID:12918",
      "type": "disease"
    },
    {
      "id": "n1",
      "type": "gene"
    },
    {
      "id": "n0",
      "curie": "DOID:1588",
      "type": "disease"
    },
    {
      "id": "n1",
      "type": "gene"
    }
  ],
  "edges": [
    {
      "id": "e0",
      "source_id": "n0",
      "target_id": "n1",
      "directed": true
    },
    {
      "id": "e0",
      "source_id": "n0",
      "target_id": "n1",
      "directed": true
    }
  ]
}
```
