### ISSUE TITLE
Using the filter on the tabular view in the name column

### ISSUE THREAD

**Issue by stevencox** [frostyfan109/tranql#116]
I get this exception 

![image](https://user-images.githubusercontent.com/306971/63131582-41b1aa80-bf8c-11e9-810d-85d64c0ec90f.png)

**Comment by stevencox** [comment]
Using this query: 
```
select chemical_substance->gene->disease
  from "/graph/gamma/quick"
 where disease="asthma"
```

**Comment by frostyfan109** [comment]
Weird. Some nodes must not have a node property.

Edit: Yep, some nodes don't have a name property. Apparently, the table viewer wasn't handling if an object didn't have the attribute that you were filtering.
