### ISSUE TITLE
Merging master to Tranql(source repo) develop branch 

### ISSUE THREAD

**Issue by YaphetKG** [frostyfan109/tranql#121]
Hi @frostyfan109 , i was merging the latest code from this fork to tranql, and had a failing travis test for it I think the failing test is ```ast_3 = tranql.parse(f"""
            SET var_str = 'CHEBI:0'
            SET var_list = ['CHEBI:22', 'CHEBI:33']
            SELECT chemical_substance->gene->disease
              FROM "/graph/gamma/quick"
             WHERE chemical_substance = [$var_str, 'CHEBI:1', $var_list]
        """)``` fails to create four quiestions of those CHEBI curies, (https://travis-ci.org/github/NCATS-Tangerine/tranql/builds/718416664)

**Comment by frostyfan109** [comment]
Thanks for opening this. I'm aware of the failing test and [opened an issue](https://github.com/frostyfan109/tranql/issues/122#issue-680399306) on what's causing it. In short, there is a bug which causes the specific feature the unit test is made for to be broken. This feature is also in the master repo and so is the bug. It's just the test which is new.

**Comment by frostyfan109** [comment]
I've fixed the bug in #122 which the unit test was addressing. There was some small reason why I hadn't already done this, but I can't seem to remember it.

**Comment by YaphetKG** [comment]
Thank you much!
