### ISSUE TITLE
Answer Viewer not working due to Robokop CORS policy

### ISSUE THREAD

**Issue by frostyfan109** [frostyfan109/tranql#27]
It seems like Robokop may have tweaked their CORS policy, because "https://robokop.renci.org/api/simple/view" can no longer be loaded by the TranQL website.

**Comment by frostyfan109** [comment]
[graph (3).zip](https://github.com/frostyfan109/tranql/files/3457568/graph.3.zip)

**Comment by frostyfan109** [comment]
![image](https://user-images.githubusercontent.com/31631417/62307975-9d3f4c80-b452-11e9-9322-8bd6b73c8309.png)

**Comment by stevencox** [comment]
What was the fix?
