### ISSUE TITLE
Unit test coverage

### ISSUE THREAD

**Issue by stevencox** [frostyfan109/tranql#73]
Ensure unit tests exist to cover
* Forward and backward associations in the select 
* Predicates work in the select
* syntax to pass values to particular reasoners in the where clause "icees.x = y"
* Requests are created to address components of the schema. RTX pieces are correctly generated to RTX.

**Comment by frostyfan109** [comment]
Ensure unit tests exist to cover
* Forward and backward associations in the select  ✔️ 
* Predicates work in the select ✔️ 
* syntax to pass values to particular reasoners in the where clause "icees.x = y" ✔️ 
* Requests are created to address components of the schema. RTX pieces are correctly generated to RTX. ✔️
