### ISSUE TITLE
Tabular data

### ISSUE THREAD

**Issue by stevencox** [frostyfan109/tranql#76]
Provide a horizontal split pane across the bottom of the view to render a tabular version of the knowledge graph. It might start with fields like:
* source node name
* source node id
* source node type
* edge type (predicate)
* target node name
* target node id
* target node type

Optionally - make the current "Find" capability an advanced search in the tabular view as a filter.

**Comment by frostyfan109** [comment]
This has been added. The find tool remains as a separate button.

Would like to fix the scrollbar to be on the table rather than the entire pane, but it looks like it's not possible due to the way that react-split-pane behaves.

**Comment by stevencox** [comment]
It looks like maybe a bit of the tabular view is lingering at the bottom of the screen?

![image](https://user-images.githubusercontent.com/306971/62567907-2cd16a80-b85a-11e9-9eb7-1dea85dfe15f.png)
