### ISSUE TITLE
Keep node properties on merge.

### ISSUE THREAD

**Issue by stevencox** [frostyfan109/tranql#78]
Merge node properties. Right now, an rtx node might overwrite a gamma node or vice versa. Instead, use dict.update() or similar to do an actual merge. One will still win where values conflict but it will be better.

**Comment by frostyfan109** [comment]
This has been added.

Nodes and edges that are merged together now go through the util.py `deep_join` function, which recursively joins iterables (without repetition) and retains other properties (theoretically should always be either equivalent or identical).

**Comment by frostyfan109** [comment]
~This method actually scares me, so this is opened to be changed.~
Replaced with a safer method that only recursively merges dictionary (rather than all iterables)
