### ISSUE TITLE
Update OpenAPI Comments and UI

### ISSUE THREAD

**Issue by stevencox** [frostyfan109/tranql#96]
Update the OpenAPI annotations in api.py and server.py to generate useful documentation.

Also update the [approach](https://github.com/NCATS-Gamma/robokop/blob/master/manager/setup.py) to generating the UI.

**Comment by stevencox** [comment]
Could we get this one into the upcoming pull request?

**Comment by frostyfan109** [comment]
- ✔️ api.py
- ✔️  server.py

**Comment by stevencox** [comment]
The API UI looks much improved. A few questions - 
* Can we get just a bit more descriptive verbiage on each of the endpoints UI about what they are supposed to do?
* Starting around [here](https://github.com/frostyfan109/tranql/blob/master/tranql/api.py#L46) there's a lot of JSON in api.py. Is there straightforward way of keeping this kind of configuration in an external yaml configuration?

No is a perfectly alright answer to the second one but it would be nice.

**Comment by frostyfan109** [comment]
1) Sure.

2) That's very doable, it is a bit out of place. The reason it's there is because api.py loads `backplane/translator_interchange.yaml` for the schemas, but that file shouldn't be directly modified. I should just move the JSON definitions into its own file and load both files.
