### ISSUE TITLE
Exception in Browse Request

### ISSUE THREAD

**Issue by stevencox** [frostyfan109/tranql#97]
The browse capability UI looks really good. This is exactly the right first step.

Browsing from a node in the answer to this query: 
```
-- What proteins are targetted by the metabolite KEGG:C00017?
set metabolite = "KEGG:C00017"
select metabolite->protein
  from "/graph/rtx"
 where metabolite=$metabolite
```

produced this:
![image](https://user-images.githubusercontent.com/306971/62403638-af0d1680-b55c-11e9-94f3-0b86a4cbf24e.png)

**Comment by frostyfan109** [comment]
I hadn't actually finished the browsing feature and, embarrassingly, never bothered to test out the requesting because I got distracted. I believe that right now either Robokop isn't working or the request is being formatted improperly.

**Comment by stevencox** [comment]
So outside of just being able to run a query in the first place, I think browse is probably my favorite feature of TranQL. Awesome.
